---
# file: roles/common/tasks/nginx.yml

- name: install nginx
  tags: nginx
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - nginx

- name: configure nginx
  tags: nginx
  copy: src={{ item.src }} dest={{ item.dest }} mode="0644"
  with_items:
    - { src: '../files/nginx.conf', dest: '/etc/nginx/nginx.conf' }
  notify:
    - restart nginx

- name: run nginx
  tags: nginx
  service: name=nginx state=running enabled=yes
