---
# redis tasks

- name: install redis
  tags: redis
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - redis-server

# - name: configure nginx
#   tags: nginx
#   copy: src={{ item.src }} dest={{ item.dest }} mode="0755"
#   with_items:
#     - { src: '../files/nginx.conf', dest: '/etc/nginx/nginx.conf' }
#   notify:
#     - restart nginx

- name: run redis
  tags: redis
  service: name=redis-server state=running enabled=yes
